// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  // a. Alterar ngOnInit para usar o modelo assíncrono com then
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros()
      .then((dados) => {
        this.livros = dados; // Atualizar o vetor "livros" com os dados obtidos
      })
      .catch((erro) => {
        console.error('Erro ao carregar os livros:', erro);
      });
  }

  // b. Assinatura do método "excluir" já está correta (parâmetro "codigo" é uma String)

  // c. Alterar o método excluir para usar then no método excluir do controlador
  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo)
      .then((sucesso) => {
        if (sucesso) {
          // Recarregar os livros após a exclusão bem-sucedida
          return this.servLivros.obterLivros();
        } else {
          console.error('Erro ao excluir o livro.');
          return [];
        }
      })
      .then((dados) => {
        this.livros = dados; // Atualizar o vetor "livros" com os dados atualizados
      })
      .catch((erro) => {
        console.error('Erro ao excluir ou recarregar os livros:', erro);
      });
  }

  obterNome = (listaEditoras: Array<Editora>, codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(listaEditoras, codEditora);
  }
}

<main class="container">
    <h1 class="h1">Catálogo de Livros</h1>
    <table class="table table-striped table-hover text-start" id="tabela">
        <thead class="table table-dark table-hover">
            <tr>
                <th scope="col">Título</th>
                <th scope="col">Resumo</th>
                <th scope="col">Editora</th>
                <th scope="col">Autores</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <tr *ngFor="let livro of livros" class="align-text-top">
                <td class="col-2 p-2">
                    <p>{{ livro.titulo }}</p>
                    <button type="button" class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td class="col-6 p-2">{{ livro.resumo }}</td>
                <td class="p-2">{{ this.obterNome(editoras, livro.codEditora) }}</td>
                <td>
                    <ul *ngFor="let autor of livro.autores">
                        <li>{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import { useState, useEffect } from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

var controleLivro = new ControleLivro();
var controleEditora = new ControleEditora();

function LinhaLivro(props) {
    var nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);
    var listaAutores = props.livro.autores;
    var listaAutoresHTML = listaAutores.map((autor, index) => (
        <li key={index.toString()}>{autor}</li>
    ));

    return (
        <tr key={props.index.toString()}>
            <td key="titulo">
                <p>{props.livro.titulo}</p>
                <button
                    type="button"
                    className="btn btn-danger"
                    onClick={() => props.excluir(props.livro.codigo)}
                >
                    Excluir
                </button>
            </td>
            <td key="resumo">{props.livro.resumo}</td>
            <td key="nomeEditora">{nomeEditora}</td>
            <td key="listaAutoresHTML">
                <ul>{listaAutoresHTML}</ul>
            </td>
        </tr>
    );
}

function LivroLista() {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    // a. Alterar "useEffect" para usar um modelo assíncrono com "then"
    useEffect(() => {
        if (!carregado) {
            controleLivro
                .obterLivros()
                .then((livrosObtidos) => setLivros(livrosObtidos))
                .catch((erro) => console.error("Erro ao carregar livros:", erro));
            setCarregado(true);
        }
    }, [carregado]);

    // b. Alterar o método "excluir" para usar "then" no controlador
    const excluir = (codigoLivro) => {
        controleLivro
            .excluir(codigoLivro)
            .then(() => setCarregado(false))
            .catch((erro) => console.error("Erro ao excluir livro:", erro));
    };

    return (
        <main>
            <h1 className="text-start">Catálogo de Livros</h1>
            <table className="table table-striped table-hover text-start">
                <thead className="table table-dark table-hover">
                    <tr>
                        <th className="col-3" scope="col">Título</th>
                        <th className="col-5" scope="col">Resumo</th>
                        <th className="col-2" scope="col">Editora</th>
                        <th className="col-2" scope="col">Autores</th>
                    </tr>
                </thead>
                <tbody className="table-group-divider">
                    {livros.map((liv, ind) => (
                        <LinhaLivro livro={liv} excluir={excluir} index={ind} key={ind} />
                    ))}
                </tbody>
            </table>
        </main>
    );
}

export default LivroLista;
