// clientes/livros-next/pages/LivroLista.tsx
import { NextPage } from "next";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import clsx from "clsx"; // Biblioteca para combinar classes
import Livro from "@/classes/modelo/Livro";
import Head from "next/head";
import { LinhaLivro } from "@/componentes/LinhaLivro";
import { Menu } from "@/componentes/Menu";
import ControleLivro from "@/classes/controle/ControleLivros"; // Substituir pelo novo ControleLivros

// b. Adicionar instância de ControleLivros
const controleLivros = new ControleLivro();

const LivroLista: NextPage = () => {
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState<boolean>(false);

  // c. Alterar a implementação de useEffect
  useEffect(() => {
    if (!carregado) {
      controleLivros
        .obterLivros()
        .then((dados) => setLivros(dados))
        .catch((erro) => console.error("Erro ao carregar livros:", erro))
        .finally(() => setCarregado(true));
    }
  }, [carregado]);

  // d. Alterar a assinatura do método "excluir" para usar código como string
  const excluir = (codigo: string) => {
    // e. Alterar a implementação de "excluir" para usar "then" no controlador
    controleLivros
      .excluir(codigo)
      .then(() => setCarregado(false))
      .catch((erro) => console.error("Erro ao excluir livro:", erro));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Catálogo Next</title>
        <meta name="description" content="Aplicativo de gestão de livros" />
      </Head>
      <Menu />
      <main className={styles.principal}>
        <h1 className="h1 mt-3">Catálogo</h1>
        <table
          className={clsx(styles.tabela, "table", "table-striped", "table-hover")}
        >
          <thead className={clsx(styles.cabecalhoTabela, "table-dark")}>
            <tr>
              <th className="col-3" scope="col">Título</th>
              <th className="col-5" scope="col">Resumo</th>
              <th className="col-2" scope="col">Editora</th>
              <th className="col-2" scope="col">Autores</th>
            </tr>
          </thead>
          <tbody className={clsx(styles.tabelaCorpo, "table-group-divider")}>
            {livros.map((liv, index) => (
              <LinhaLivro key={index} livro={liv} excluir={excluir} />
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  // a. Alterar ngOnInit para usar o modelo assíncrono com then
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros()
      .then((dados) => {
        this.livros = dados; // Atualizar o vetor "livros" com os dados obtidos
      })
      .catch((erro) => {
        console.error('Erro ao carregar os livros:', erro);
      });
  }

  // b. Assinatura do método "excluir" já está correta (parâmetro "codigo" é uma String)

  // c. Alterar o método excluir para usar then no método excluir do controlador
  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo)
      .then((sucesso) => {
        if (sucesso) {
          // Recarregar os livros após a exclusão bem-sucedida
          return this.servLivros.obterLivros();
        } else {
          console.error('Erro ao excluir o livro.');
          return [];
        }
      })
      .then((dados) => {
        this.livros = dados; // Atualizar o vetor "livros" com os dados atualizados
      })
      .catch((erro) => {
        console.error('Erro ao excluir ou recarregar os livros:', erro);
      });
  }

  obterNome = (listaEditoras: Array<Editora>, codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(listaEditoras, codEditora);
  }
}

<main class="container">
    <h1 class="h1">Catálogo de Livros</h1>
    <table class="table table-striped table-hover text-start" id="tabela">
        <thead class="table table-dark table-hover">
            <tr>
                <th scope="col">Título</th>
                <th scope="col">Resumo</th>
                <th scope="col">Editora</th>
                <th scope="col">Autores</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <tr *ngFor="let livro of livros" class="align-text-top">
                <td class="col-2 p-2">
                    <p>{{ livro.titulo }}</p>
                    <button type="button" class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td class="col-6 p-2">{{ livro.resumo }}</td>
                <td class="p-2">{{ this.obterNome(editoras, livro.codEditora) }}</td>
                <td>
                    <ul *ngFor="let autor of livro.autores">
                        <li>{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
